name: Build Windows MSI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore
      run: dotnet restore src/SaikyoVpn.sln

    - name: Build and publish GUI
      run: dotnet publish src/SaikyoVpn.Gui/SaikyoVpn.Gui.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./artifacts/gui

    - name: Build and publish Service
      run: dotnet publish src/SaikyoVpn.Service/SaikyoVpn.Service.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./artifacts/service

    - name: Install WiX via choco
      run: choco install wix -y

    - name: Create MSI (candle + light)
      working-directory: installer
      run: |
        set PATH=%PATH%;"C:\Program Files (x86)\WiX Toolset v3.11\bin"
        if not exist "..\artifacts\gui" echo GUI artifacts missing
        if not exist "..\artifacts\service" echo Service artifacts missing
        candle.exe SaikyoInstaller.wxs -o SaikyoInstaller.wixobj
        light.exe SaikyoInstaller.wixobj -o SaikyoVpn-Installer.msi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: saikyo-artifacts
        path: |
          artifacts/**
          installer/SaikyoVpn-Installer.msi
